# Generated by Django 5.0.6 on 2024-07-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careeravailability',
            name='position',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
