# Generated by Django 5.0.6 on 2024-07-09 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming_Events', '0003_ratingevent_delete_upcomingeventswallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingevent',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upcoming_Events.upcomingevents'),
            preserve_default=False,
        ),
    ]
