# Generated by Django 5.0.6 on 2024-07-10 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming_Events', '0005_upcomingeventsbooked'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEventsBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_ticket', models.BigIntegerField()),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upcoming_Events.upcomingevents')),
            ],
        ),
    ]
