# Generated by Django 5.0.6 on 2024-07-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming_Events', '0008_remove_upcomingeventsbooked_numberoftickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingeventsbooked',
            name='no_ticket',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
